### ISSUE TITLE
Problem of HTTP 404 when clicking login button 

### ISSUE THREAD

**Issue by prakhar19970** [javabyranjith/spring-framework-mvc#1]
Sir, i have tried to look for the solutions over the internet , i had run the same spring mvc login example home.jsp is displayed fine but futher when I click on login or register there is an HTTPs 404 error 
![screenshot 36](https://user-images.githubusercontent.com/38586639/42217478-01cfb7da-7ee3-11e8-9629-efbc8f105d64.png)

**Comment by javabyranjith** [comment]
From your screenshot, seems there are some errors in your java resources. could you try to run again after resolving those issues?

**Comment by prakhar19970** [comment]
Sir ,I have a request if you don't mind ....
Can I send the program which I have on my device , because I checked my
resources , specially the userbean .XML, I am working on a webbased project
and I need login section in that , so I am referring to your code .
Please allow me send the code which I tried to run .

**Comment by javabyranjith** [comment]
sure. zip the whole project and send my email java2ranjith@gmail.com

**Comment by prakhar19970** [comment]
Ok sir I have sent it

**Comment by prakhar19970** [comment]
thankyou sir problem is resolved
